### ISSUE TITLE
Setup continuous AppImage builds

### ISSUE THREAD

**Issue by Symbian9** [francescmm/GitQlient#70]
Please, setup Travis CI for auto-build *AppImage* (portable package for Linux) for each commit & upload resulted binary:

- AppImage Docs - https://docs.appimage.org/

### TODO

0. [x] Create `../blob/master/.travis.yml`
1. https://github.com/appimage/AppImageKit
1.1. https://github.com/probonopd/linuxdeployqt
1.2. https://github.com/linuxdeploy
2. https://github.com/probonopd/uploadtool
3. [ ] Enable Travis CI pushing `continuous` builds to GitHub releases for this repo.
4. [ ] https://github.com/francescmm/GitQlient/releases/tag/continuous

For example, take a look on *LeoCAD* `.travis.yml` implementation:

- https://github.com/leozide/leocad/blob/master/.travis.yml

And here is how resulted builds would look like:

- https://github.com/leozide/leocad/releases/tag/continuous

For any AppImage packaging questions & support:

- https://docs.appimage.org/user-guide/faq.html#question-where-do-i-get-support

**Comment by francescmm** [comment]
Hi @Symbian9, thanks for the input!

What would be in your opinion the gain of having an AppImage for completely unstable commits?

**Comment by Symbian9** [comment]
> What would be in your opinion the gain of having an AppImage for completely unstable commits?

From other side, continuous AppImage would include latest fixes.

**Comment by francescmm** [comment]
The thing is that my plan is to release fixes in minor versions like the one I'm preparing. These minors go into it's how branch and they follow the schema: alpha, beta, rc, and release. I can trigger an AppImage for each step, no problems. But that would be all since everything else is pure development. This is the same behaviour has it will be for major releases.

In the other hand, if there is a critical bug and needs a quick patch, it will be release straight-forward. Without betas and directly into master and tagged. Since it's tagged it will have its own AppImage.

If these are not the cases, do you mean having an AppImage for something like an "unstable" branch?

**Comment by Symbian9** [comment]
> If these are not the cases, do you mean having an AppImage for something like an "unstable" branch?

Yep, like "nightly" builds for testers.

**Comment by francescmm** [comment]
I see. I can set it up for the v1.2.0 :)

But if you want it before that, PR the change if you can do it in a fork.

**Comment by francescmm** [comment]
Hi,

I've been checking the script used on LeoCAD for the continuous builds and I've decided to not continue with the nightly builds for several resons:

* Build systems and CI is not my area of expertise and I'm actually taking care of more than I wanted. In addition, the complexity of the script makes me not have the time to go through and adapt it to the project needs.
* I won't release nightly builds as LeoCAD is doing.The only releases with binaries I'll support are the patches, minors and majors. This will prevent testing on really unstable development where I don't see the point of doing it since it would be in the middle of a feature development.

There is a planning in the Wiki were I've set a month for testing of the different versions. Every Major and Minor will have an _alpha_, _beta_ and _release candidate_ version to test. Patches will be release directly since they're meant to be quick urgent fixes.
